### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by kcore** [vivek3singh/longest-matrix-app#1]
For input
`01101,11010,01110,11010,11111`

**Comment by singvivc** [comment]
May i know how you are executing the code with that input

curl http://localhost:8081/longestmatrix?param=01101,11010,01110,11110,11111

**Comment by kcore** [comment]
From the browser AND postman as well

**Comment by vivek3singh** [comment]
Hi,
    I made the correction. The code was throwing RuntimeException.
I made the necessary changes, and committed it back. Can you please recheck and let me know if you find any issue?
